# SPDX-FileCopyrightText: 2024 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

---
services:
  # ejbca and DB services here
  serles-acme:
    environment:
      - CA_NAME=Org Name CA
      - CERT_PROFILE=ACMECertCert
      - ENTITY_PROFILE=ACMEEntityProfile
    image: ghcr.io/joepitt91/serles-acme-docker:main
    # or
    # image: joepitt91/serles-acme:latest
    ports:
      - 127.0.0.1:8000:8000
    restart: unless-stopped
    volumes:
      - ./serles-acme:/etc/serles/
