# SPDX-FileCopyrightText: 2024 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Build Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Project
        uses: actions/checkout@v4
      - id: docker-login
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
      - id: setup-buildx
        name: Setup Docker buildx Environment
        uses: docker/setup-buildx-action@v3
      - id: build
        name: Build
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/serles-acme:latest -t ${{ vars.DOCKERHUB_USERNAME }}/serles-acme:1.1.0 .
      - id: push
        name: Push
        run: |
          docker image push ${{ vars.DOCKERHUB_USERNAME }}/serles-acme:1.1.0
          docker image push ${{ vars.DOCKERHUB_USERNAME }}/serles-acme:latest
